### ISSUE TITLE
Hide generic model names or prefix them

### ISSUE THREAD

**Issue by tshedor** [bugsnag/bugsnag-flutter#128]
### Description

When importing `bugsnag_flutter/bugsnag_flutter.dart`, internal Bugsnag models are exposed. `App`, `User`, `Session` are class names commonly used within implementations. The import causes a conflict within Dart because now there are two `User` classes exposed by different imports.

**Describe the solution you'd like**

1. Prefix the models to the Bugsnag domain. `BugsnagClient`, `BugsnagUser`, `BugsnagApp`. 
2. Do not export these models in `bugsnag_flutter.dart` (my personal choice; as a maintainer, the less I expose the more I can refactor without worrying about implementers). 

**Describe alternatives you've considered**

Generally I'll use `show bugsnag` to restrict my access to just the global singleton, which is 95 percent the only thing I need (save `BreadcrumbType` and `BugsnagNavigatorObserver`).

**Comment by luke-belton** [comment]
Hi @tshedor - thanks for raising this, our Flutter team are going to investigate and we'll keep you updated on this thread.

**Comment by luke-belton** [comment]
Hi @tshedor - this was released in [v2.0.2](https://github.com/bugsnag/bugsnag-flutter/releases/tag/v2.0.2) of `bugsnag-flutter` 🎉 

Our engineering team chose to prefix all class named with `Bugsnag` to avoid clashing with application code so you will need to make some changes in your code if you're using any of the exported classes (e.g. if setting a user with `BugsnagUser` inside your call to `Bugsnag.start`).
