### ISSUE TITLE
zun zoned error  

### ISSUE THREAD

**Issue by J-Nokwal** [bugsnag/bugsnag-flutter#197]
The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
When the exception was thrown, this was the stack
#0      BindingBase.debugCheckZone.<anonymous closure>
binding.dart:497
#1      BindingBase.debugCheckZone
binding.dart:502
#2      runApp
binding.dart:1080
#3      main.<anonymous closure>
main.dart:40
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════

Future<void> main() => bugsnag.start(
      apiKey: 'mykey',
      runApp: () async {
        WidgetsFlutterBinding.ensureInitialized();
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
        await configureDependencies();
        // FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
        runApp(const MyApp());
      },
    );

  zone mismatched error for this code

**Comment by YuxuanDu** [comment]
The plugin is outdated. They need to update their plugin to meet the new error collection requirement.
Instead of creating a new Zone, PlatformDispatcher must be used for error collection.

Also, don't update Gradle to 8, the plugin is not compatible yet.

**Comment by matth-bugsnag** [comment]
Hi @J-Nokwal, 

Thanks for reaching out. 

I just wanted to let you know that we are aware of this issue and have an item on our roadmap aimed at replacing these deprecating Zone calls. We don't currently have an ETA for the release of this fix but we will be sure to keep you informed of any updates.

**Comment by diego-tread** [comment]
@matth-bugsnag Thanks for the response. I am also running into this issue, while evaluating whether to use bugsnag as a vendor for my team. Any update on a fix ETA?

**Comment by jeroenbell** [comment]
I happened to be looking at bugsnag as one of the integrations for my team as well. I'm also running into the same issue.

**Comment by brokenicedeveloper** [comment]
@matth-bugsnag any update on this?

**Comment by johnkiely1** [comment]
Hi @brokenicedeveloper, we are working on this at present and are hopeful of having an update soon.

**Comment by alanlanglois** [comment]
@johnkiely1 good luck, let us know when the fix is ready, Best!

**Comment by maxim-ivanchuk-idf** [comment]
@johnkiely1 waiting)))

**Comment by MohamedAshraf701** [comment]
I encountered a similar issue and was able to find a solution. The problem was caused by multiple zones, and the application needed to run on only one zone. The following code snippet was helpful to me:

Zone.root.runGuarded(() {
  runApp(MyApp());
});

**Comment by johnkiely1** [comment]
Hi all, just a quick update, we have the changes in what we hope is their final stages of testing now. Unless we get any major problems, we hope to release this next week.

**Comment by johnkiely1** [comment]
Hey all, just wanted to let you know we have now released [v3.0.0](https://github.com/bugsnag/bugsnag-flutter/releases/tag/v3.0.0) which should address the issue. 

We have also created an upgrading guide [here](https://github.com/bugsnag/bugsnag-flutter/blob/v3.0.0/UPGRADING.MD) as there are some additional changes from bugsnag-flutter v2

Do let us know if you see any issues when you upgrade.
