### ISSUE TITLE
PlatformException(NullPointerException...........)

### ISSUE THREAD

**Issue by jbankz** [bugsnag/bugsnag-flutter#201]
### Describe the bug
I keep running into this error randomly with no true report as to what the cause may be.

![Screenshot 2023-07-02 at 12 22 52](https://github.com/bugsnag/bugsnag-flutter/assets/29983299/0bdcb2ad-db82-44b5-a31e-81a8ddd02980)

### Steps to reproduce

There is no clear way to reproduce this error as it occurs randomly and when not expected.

### Environment

- Bugsnag version:=>  bugsnag_flutter: ^2.4.0
- Flutter version:=> Flutter 3.10.5 • channel stable
</details>

**Comment by yairsts** [comment]
I get this error randomly all the time. this is critical issue

**Comment by johnkiely1** [comment]
Hi @jbankz @yairsts , thanks, we are investigating this now.

**Comment by yairsts** [comment]
I reproduced that
Press back (android) until the application closed.
Then, reopen the app.
Good luck

**Comment by johnkiely1** [comment]
Hi @jbankz @yairsts , this should now be fixed in [v2.5.0](https://github.com/bugsnag/bugsnag-flutter/releases/tag/v2.5.0)
