### ISSUE TITLE
Navigator.pushAndRemoveUntil throws exception in Bugsnag

### ISSUE THREAD

**Issue by Ghoelian** [bugsnag/bugsnag-flutter#238]
### Describe the bug

When calling```Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (context) => const Screen()), (route) => false)```, Bugsnag throws an exception somewhere in a method channel.

### Steps to reproduce
I was able to reproduce this with the default new Flutter project.

1. Create new Flutter project
2. Add at least one extra widget
3. Navigate between them using ```Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (context) => const Screen()), (route) => false)```

### Environment

- Bugsnag version: 3.0.2
- Flutter version: 3.0.2
- Flutter-first app or native app with Flutter component(s): Flutter-first
- iOS/Android version: Running on Android 12, build target 34
- Simulator/emulator or physical device: Physical

### Example Repo 

https://codeberg.org/Ghoelian/bugsnag-navigate-issue

<details><summary>Error messages:</summary>

```
PlatformException(ClassCastException, org.json.JSONObject$1 cannot be cast to java.lang.String, [com.bugsnag.flutter.BugsnagFlutter.setContext(BugsnagFlutter.java:244), com.bugsnag.flutter.BugsnagFlutterPlugin$$ExternalSyntheticLambda6.invoke(Unknown Source:4), com.bugsnag.flutter.BugsnagFlutterPlugin.onMethodCall(BugsnagFlutterPlugin.java:66), io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267), io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292), io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319), io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12), android.os.Handler.handleCallback(Handler.java:938), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loopOnce(Looper.java:201), android.os.Looper.loop(Looper.java:288), android.app.ActivityThread.main(ActivityThread.java:7891), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)], null)
E/flutter (12718): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:170:7)
E/flutter (12718): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (12718): <asynchronous suspension>
E/flutter (12718): 
```

</details>

**Comment by Ghoelian** [comment]
I just noticed there's a separate repo for this, https://github.com/bugsnag/bugsnag-flutter-navigator-observer, which states that this is not a production-ready package.

But it does seem to be included in the base bugsnag_flutter package, and is referred to in the [docs](https://docs.bugsnag.com/platforms/flutter/customizing-breadcrumbs/#navigation-breadcrumbs) without any warnings. Should I not be using this yet?

**Comment by clr182** [comment]
Hi @Ghoelian 
Thank you for reaching out. This does look to be an issue on our side. We are investigating this further and will be sure to update you when priorities allow. 

In regards to the repo linked in your comment, this is actually a different package, not one used in the notifier and was originally intended as a new common package for the Error SDK and performance SDK. However this is no longer going to be used and will soon be removed.

**Comment by mclack** [comment]
Hi @Ghoelian 

We have just released a new version of the BugSnag Flutter notifier ([v3.1.1](https://github.com/bugsnag/bugsnag-flutter/releases/tag/v3.1.1)) which should solve your issue with exceptions being thrown by `Navigator.pushAndRemoveUntil`.

If you are still seeing this issue after updating to the latest version of the Flutter notifier, then please let us know and we can investigate further.
