### ISSUE TITLE
Wrong bugsnag start implementation

### ISSUE THREAD

**Issue by TobiasRump** [bugsnag/bugsnag-flutter#256]
Inside the web tutorial to implement the first example of bugsnag with flutter it says at the second step, that we need to implement:

#### Basic Configuration
_Wrap your application with bugsnag.start to start capturing errors:_

```
import 'package:bugsnag_flutter/bugsnag_flutter.dart';

void main() => bugsnag.start(
  apiKey: 'key',
  runApp: () => runApp(const MyFlutterApp()),
);
````

#### But its not working anymore, because there is no "runApp" property inside `bugsnag.start()` Inside the comments of the start function it says right:

_Typical Flutter-only applications with Bugsnag will start with:_

```
import 'package:bugsnag_flutter/bugsnag_flutter.dart';

Future<void> main() async {
  await bugsnag.start(apiKey: 'your-api-key');
  runApp(MyApplication());
}
```

**Comment by clr182** [comment]
Hi @TobiasRump 

Thank you for sharing this feedback. 

[The documentation](https://docs.bugsnag.com/platforms/flutter/#basic-configuration) has been updated to show the correct bugsnag.start implementation: 
```
import 'package:bugsnag_flutter/bugsnag_flutter.dart';

Future<void> main() async {
   await bugsnag.start(apiKey: 'your-api-key');
   runApp(MyApplication());
}```
