### ISSUE TITLE
lStar not found

### ISSUE THREAD

**Issue by jbankz** [bugsnag/bugsnag-flutter#261]
### Describe the bug

I keep getting this error 

> * What went wrong:
Execution failed for task ':bugsnag_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/ktf-web/.gradle/caches/transforms-3/55b0a2fe1bf295c40c4062d8395f6212/transformed/core-1.13.1/res/values/values.xml:113:5-122:25: AAPT: error: resource android:attr/lStar not found.

on the latest bugsnag version  => bugsnag_flutter: ^4.0.0

</details>

**Comment by clr182** [comment]
Hi @jbankz 

This error is due to a mismatch in the Android SDK versions being used across dependencies. Can you please let us know which SDKVersion you have set in your `build.gradle` file? i.e. 
``` 
android {
    compileSdkVersion 31
}
```

**Comment by jbankz** [comment]
> Hi @jbankz
> 
> This error is due to a mismatch in the Android SDK versions being used across dependencies. Can you please let us know which SDKVersion you have set in your `build.gradle` file? i.e.
> 
> ```
> android {
>     compileSdkVersion 31
> }
> ```
> 
> The error `AAPT: error: resource android:attr/lStar not found` could be due to your use of an older SDK version, as lStar was introduced in Android SDK 31. Use of an older SDK version would explain why this is not able to be found for your project.

Hi @clr182  i am using compileSdkVersion 34, i was able to by pass the issue running the app using FVM

**Comment by clr182** [comment]
Hi @jbankz 

Glad you were able to solve this issue. It sounds like there might have been a version mismatch between the Flutter environment you were initially using and the one managed by FVM. If you run into any other issues or need further assistance with this setup, feel free to ask and we can re-open this issue.
